import React from 'react';
import { AlertTriangle, CheckCircle, X } from 'lucide-react';

const LegalDisclaimerModal = ({ isOpen, onClose, onAccept }) => {
  console.log('LegalDisclaimerModal render - isOpen:', isOpen);
  if (!isOpen) return null;

  const handleBackdropClick = (e) => {
    if (e.target === e.currentTarget) {
      onClose();
    }
  };

  return (
    <div 
      className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4"
      onClick={handleBackdropClick}
    >
      <div className="bg-white rounded-lg shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          {/* Header */}
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center">
              <AlertTriangle className="text-yellow-600 mr-3" size={24} />
              <h2 className="text-2xl font-bold text-gray-900">Legal Disclaimer</h2>
            </div>
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-gray-600 transition-colors"
            >
              <X size={24} />
            </button>
          </div>

          {/* Content */}
          <div className="space-y-4 text-gray-700 leading-relaxed">
            <p>
              This web tool is provided solely for the purpose of assisting in the drafting of comment letters on regulatory or administrative matters. The tool utilizes generative Artificial Intelligence (AI) to produce the comment letters based on user-provided data. AI-generated content may be inaccurate, incomplete, or outdated. The content generated by this tool is for informational and drafting assistance only and does not constitute legal advice or political advocacy.
            </p>

            <p>
              Users are solely responsible for reviewing and verifying the content's accuracy and ensuring compliance with applicable legal, regulatory, and tax requirements. NCRC and its affiliates make no representations or warranties as to the accuracy, reliability, or suitability of any generated content and disclaim all liability arising from its use. Users assume full responsibility for any reliance on or dissemination of the generated content and must ensure that the final work is error-free and suitable to their specific needs.
            </p>

            <p>
              As a §501(c)(3) tax-exempt organization, NCRC does not engage in or support any political campaign activity, partisan advocacy, or lobbying outside the limits permitted by law. Any references produced by this tool that could be interpreted as political in nature are unintentional and do not reflect the view or positions of NCRC.
            </p>

            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <p className="text-blue-800 font-medium">
                By using this tool, you acknowledge and agree to the terms.
              </p>
            </div>
          </div>

          {/* Actions */}
          <div className="flex justify-end space-x-4 mt-8 pt-6 border-t border-gray-200">
            <button
              onClick={onClose}
              className="px-6 py-2 text-gray-600 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={onAccept}
              className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center"
            >
              <CheckCircle size={16} className="mr-2" />
              I Agree & Continue
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LegalDisclaimerModal;
