name: Setup GitHub Secrets

on:
  workflow_dispatch:
    inputs:
      gcp_project_id:
        description: 'Google Cloud Project ID'
        required: true
        type: string
      service_account_key:
        description: 'Service Account Key JSON (paste the entire JSON)'
        required: true
        type: string

jobs:
  setup-secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      secrets: write
    
    steps:
    - name: Setup secrets
      run: |
        echo "Setting up GitHub secrets for deployment..."
        
        # Set GCP Project ID
        echo "GCP_PROJECT_ID=${{ github.event.inputs.gcp_project_id }}" >> $GITHUB_ENV
        
        # Extract values from service account key
        echo "${{ github.event.inputs.service_account_key }}" > /tmp/sa-key.json
        
        # Extract individual values
        BQ_PROJECT_ID=$(jq -r '.project_id' /tmp/sa-key.json)
        BQ_TYPE=$(jq -r '.type' /tmp/sa-key.json)
        BQ_PRIVATE_KEY_ID=$(jq -r '.private_key_id' /tmp/sa-key.json)
        BQ_PRIVATE_KEY=$(jq -r '.private_key' /tmp/sa-key.json)
        BQ_CLIENT_EMAIL=$(jq -r '.client_email' /tmp/sa-key.json)
        BQ_CLIENT_ID=$(jq -r '.client_id' /tmp/sa-key.json)
        BQ_AUTH_URI=$(jq -r '.auth_uri' /tmp/sa-key.json)
        BQ_TOKEN_URI=$(jq -r '.token_uri' /tmp/sa-key.json)
        BQ_AUTH_PROVIDER_X509_CERT_URL=$(jq -r '.auth_provider_x509_cert_url' /tmp/sa-key.json)
        BQ_CLIENT_X509_CERT_URL=$(jq -r '.client_x509_cert_url' /tmp/sa-key.json)
        
        echo "✅ Extracted BigQuery credentials from service account key"
        echo "📋 Next steps:"
        echo "1. Go to Repository Settings → Secrets and variables → Actions"
        echo "2. Add the following secrets:"
        echo ""
        echo "GCP_PROJECT_ID = ${{ github.event.inputs.gcp_project_id }}"
        echo "GCP_SA_KEY = <paste the entire service account JSON>"
        echo "BQ_PROJECT_ID = $BQ_PROJECT_ID"
        echo "BQ_TYPE = $BQ_TYPE"
        echo "BQ_PRIVATE_KEY_ID = $BQ_PRIVATE_KEY_ID"
        echo "BQ_PRIVATE_KEY = $BQ_PRIVATE_KEY"
        echo "BQ_CLIENT_EMAIL = $BQ_CLIENT_EMAIL"
        echo "BQ_CLIENT_ID = $BQ_CLIENT_ID"
        echo "BQ_AUTH_URI = $BQ_AUTH_URI"
        echo "BQ_TOKEN_URI = $BQ_TOKEN_URI"
        echo "BQ_AUTH_PROVIDER_X509_CERT_URL = $BQ_AUTH_PROVIDER_X509_CERT_URL"
        echo "BQ_CLIENT_X509_CERT_URL = $BQ_CLIENT_X509_CERT_URL"
        echo "BIGQUERY_DATASET = cfpb"
        echo ""
        echo "3. Add your Claude API key:"
        echo "CLAUDE_API_KEY = <your-claude-api-key>"
        echo "CLAUDE_MODEL = claude-3-sonnet-20240229"
        echo ""
        echo "4. Add reCAPTCHA keys (if using):"
        echo "RECAPTCHA_SITE_KEY = <your-recaptcha-site-key>"
        echo "RECAPTCHA_SECRET_KEY = <your-recaptcha-secret-key>"
        echo ""
        echo "5. After deployment, update CLIENT_URL with your Cloud Run service URL"
        
        # Clean up
        rm /tmp/sa-key.json
